### ISSUE TITLE
screenshare in rocketchat ios client even possible?

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.ScreenShare.Extensions#4]
Hello Devs.

screensharing when in browser works good but when i try to initiate a screensharing session from within the ios client i get a "install extension" window. Is that a wanted behaviour?

thanks and cheers
t.

**Comment by geekgonecrazy** [comment]
@himbeere it is not.  Please create an issue on the https://github.com/rocketchat/rocket.chat repo so we can look at disabling this button on mobile.   This repo specifically is for adding the screensharing functionality to the browser
